# Generated by IBM TransformationAdvisor
# Wed Jan 31 13:39:44 UTC 2024

FROM icr.io/appcafe/ibm-semeru-runtimes:open-8-jdk-focal AS build-stage

RUN apt-get update && \
    apt-get install -y maven unzip

COPY . /project
WORKDIR /project

#RUN mvn process-resources

RUN mkdir -p /config/lib && \
     cp ./target/*.*ar /config && \
     if [ -d "./target/lib" ]; then \
         cp ./target/lib/*.* /config/lib; \
     fi

FROM icr.io/appcafe/websphere-traditional:latest

# put app and scripts and properties in /work/config
# put external library (e.g db driver) in /work/config/lib
COPY --chown=was:root --from=build-stage /config /work/config
COPY --chown=was:root ./src/config /work/config
COPY --chown=was:root ./lib /work/config/lib
RUN /work/configure.sh
