apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mod-app
  namespace: openshift-gitops
spec:
  destination:
    namespace: wtmod
    server: https://kubernetes.default.svc 
  project: default 
  source: 
    path: deploy/RCO
    repoURL: https://github.com/barnsie007/modResorts.git
    targetRevision: main
  syncPolicy: 
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
